module.exports = {
	labelData:[
			{label:'基站类型',id:1,prop:'',type:'title',selected:1},
			{label:'基站细分类型',prop:'stationType',type:'select',selected:1,key:'stationType',title:'basicForm'},
			{label:'基站名称',prop:'stationName',type:'input',selected:1,title:'basicForm'},
			{label:'基站基础属性',prop:'',type:'title',selected:2},
			{label:'所属区域',prop:'areaCode',type:'areaSelect',selected:2,title:'basicForm'},
			{label:'基站详细地址',prop:'address',type:'input',selected:2,title:'basicForm'},
			// {label:'机楼名称',prop:'type',type:'input',selected:2,},
			// {label:'所在楼层',prop:'type',type:'select',key:'useStatus',selected:2,},
			{label:'基站状态',prop:'status',type:'select',selected:2,key:'stationStatus',title:'basicForm'},
			{label:'基站二级状态',prop:'secondStatus',type:'select',selected:2,key:'stationSecondStatus',title:'basicForm'},
			{label:'投产时间',prop:'startTime',type:'time',selected:2,title:'basicForm'},
			{label:'基站保障等级',prop:'protectionLevel',type:'select',selected:2,key:'protectionLevel',title:'basicForm'},
			{label:'基站地形',prop:'terrain',type:'select',selected:2,key:'terrain',title:'basicForm'},
			{label:'气候分区',prop:'weather',type:'select',selected:2,key:'weather',title:'basicForm'},
			{label:'经度',prop:'lng',type:'number',selected:2,title:'basicForm'},
			{label:'纬度',prop:'lat',type:'number',selected:2,title:'basicForm'},
			{label:'FSU是否安装',prop:'fsuInstallStatus',type:'select',selected:2,key:'basic',title:'basicForm'},
			{label:'FSU状态',prop:'fsuStatus',type:'select',selected:2,key:'fsuStatus',title:'basicForm'},
			{label:'FSU交维时间',prop:'fsuHandoverTime',type:'time',selected:2,title:'basicForm'},
			
			{label:'物业信息',id:3,prop:'',type:'title',selected:3,},
			{label:'物业属性',prop:'realEstateAttr',type:'select',selected:4,key:'realEstateAttr',title:'stationExtendInfo'},
			{label:'物业联系人',prop:'realEstateContacts',type:'input',selected:4,title:'stationExtendInfo'},
			{label:'物业联系电话',prop:'realEstatePhone',type:'input',key:'useStatus',selected:4,title:'stationExtendInfo'},
			{label:'0-6点是否可以上站',prop:'getInStation',type:'select',selected:4,key:'basic',title:'stationExtendInfo'},
			{label:'上站难易程度',prop:'getInStationDiffLevel',type:'select',selected:4,key:'getInStationDiffLevel',title:'stationExtendInfo'},
			{label:'上站困难原因',prop:'getInStationDiffReason',type:'select',selected:4,key:'getInStationDiffReason',title:'stationExtendInfo'},
			{label:'市电信息',id:4,prop:'stieName',type:'title',selected:5,title:'stationExtendInfo'},
			{label:'供电方式（一级）',prop:'powerSupplyModeFirst',type:'select',selected:5,key:'powerSupplyModeFirst',title:'stationExtendInfo'},
			{label:'供电方式（二级）',prop:'powerSupplyModeSecond',type:'select',selected:5,key:'powerSupplyModeSecond',title:'stationExtendInfo'},
			{label:'所属供电公司名称',prop:'powerSupplyCompany',type:'input',selected:5,title:'stationExtendInfo'},
			{label:'所属电力路线名称',prop:'powerLineName',type:'input',selected:5,title:'stationExtendInfo'},
			{label:'供电部门电话',prop:'powerSupplyDeptPhone',type:'input',selected:5,title:'stationExtendInfo'},
			{label:'是否具备发电条件',prop:'powerGenerationCondition',type:'select',selected:5,key:'basic',title:'stationExtendInfo'},
			{label:'蓄电池基础保障服务（小时）',prop:'batterySupportExtraTime',type:'integer',selected:5,title:'stationExtendInfo'},
			{label:'蓄电池额外保障服务（小时）',prop:'batterySupportTime',type:'integer',selected:5,title:'stationExtendInfo'},
			{label:'发电等待时长（分钟）',prop:'generationWaitingTime',type:'integer',selected:5,title:'stationExtendInfo'},
			{label:'0-6点是否可以上站发电',prop:'getInStationPowerGeneration',type:'select',selected:5,key:'basic',title:'stationExtendInfo'},
			{label:'发电电压限制（v）',prop:'voltageGateRestriction',type:'select',selected:5,key:'voltageGateRestriction',title:'stationExtendInfo'},
			{label:'发电所需油机功率（kw）',prop:'requiredEnginePower',type:'integer',selected:5,title:'stationExtendInfo'},
			{label:'是否有固定油机',prop:'fixedOilMachine',type:'select',selected:5,key:'basic',title:'stationExtendInfo'},
			{label:'运营商共享情况',id:2,prop:'',type:'title',selected:3,},
			// {label:'运营商共享情况',prop:'sharingCondition',type:'select',key:'operator',change:true,selected:3,multiple:true,},
	],
	// 运营商共享情况
	linkData:[
			{label:'公司站型',prop:'stationType',type:'select',selected:3,key:'stationType'},
			{label:'设备制式',prop:'deviceStandard',type:'select',selected:3,key:'deviceStandard'},
			{label:'基站维护服务等级',prop:'preserveLevel',type:'select',selected:3,key:'preserveLevel'},
			{label:'是否购买发电服务',prop:'powerGenerationService',type:'select',selected:3,key:'basic'},
			{label:'起租时间',prop:'rentStartTime',type:'time',selected:3},
			{label:'租期（年）',prop:'rentTerm',type:'input',selected:3},
			{label:'租期截止时间',prop:'rentEndTime',type:'time',selected:3},
	],
	// 运营商共享情况
	// shareConditionsKey:[
	// 	{label:'公司站型',prop:'stationType',selected:2},
	// 	{label:'设备制式',prop:'deviceStandard',selected:2},
	// 	{label:'基站维护服务等级',prop:'preserveLevel',selected:2},
	// 	{label:'是否购买发电服务',prop:'powerGenerationService',selected:2},
	// 	{label:'起租时间',prop:'rentStartTime',selected:2},
	// 	{label:'租期（年）',prop:'rentTerm',selected:2},
	// 	{label:'租期截止时间',prop:'rentEndTime',selected:2},
	// ],
	// 物业信息
	stationExtendInfoKey:[
		{label:'物业属性',prop:'realEstateAttr',selected:3},
		{label:'物业联系人',prop:'realEstateContacts',selected:3},
		{label:'物业联系电话',prop:'realEstatePhone',selected:3},
		{label:'0-6点是否可以上站',prop:'getInStation',selected:3},
		{label:'上站难易程度',prop:'getInStationDiffLevel',selected:3},
		{label:'上站困难原因',prop:'getInStationDiffReason',selected:3},
	],
	// 市电信息
	stationExtendInfoKey2:[
		{label:'供电方式（一级）',prop:'powerSupplyModeFirst',selected:4},
		{label:'供电方式（二级）',prop:'powerSupplyModeSecond',selected:4},
		{label:'所属供电公司名称',prop:'powerSupplyCompany',selected:4},
		{label:'所属电力路线名称',prop:'powerLineName',selected:4},
		{label:'供电部门电话',prop:'powerSupplyDeptPhone',selected:4},
		{label:'是否具备发电条件',prop:'powerGenerationCondition',selected:4},
		{label:'蓄电池基础保障服务（小时）',prop:'batterySupportExtraTime',selected:4},
		{label:'蓄电池额外保障服务（小时）',prop:'batterySupportTime',selected:4},
		{label:'发电等待时长（分钟）',prop:'generationWaitingTime',selected:4},
		{label:'0-6点是否可以上站发电',prop:'getInStationPowerGeneration',selected:4},
		{label:'发电电压限制（v）',prop:'voltageGateRestriction',selected:4},
		{label:'发电所需油机功率',prop:'requiredEnginePower',selected:4},
		{label:'是否有固定油机',prop:'fixedOilMachine',selected:4},
	],
	// 基站历史维修
	historyMaintenanceListKey:[
		{label:'维修',prop:'additionalProperty1',type:'areaSelect',selected:5},
	],
	// 基站历史告警
	historyAlarmListKey:[
		{label:'告警',prop:'additionalProperty1',type:'areaSelect',selected:5},
	],
	// 预览设备信息
	devicePreviewsKey:[
		{label:'所属区域',prop:'area'},
		{label:'设备编号',prop:'deviceCode'},
		{label:'设备名称',prop:'deviceName'},
		{label:'告警',prop:'deviceSecondType'},
		{label:'告警',prop:'deviceType'},
	],
	// 基站基本信息
	stationBasicKey:[
		{label:'基站编码',prop:'stationCode',selected:1},
		{label:'基站细分类型',prop:'stationType',selected:1},
		{label:'所属区域',prop:'area',selected:1},
		{label:'基站详细地址',prop:'address',selected:1},
		// {label:'机楼名称',prop:'type',selected:1},
		// {label:'所在楼层',prop:'type',selected:1},
		{label:'基站状态',prop:'status',selected:1},
		{label:'基站二级状态',prop:'secondStatus',selected:1},
		{label:'投产时间',prop:'startTime',selected:1},
		{label:'基站保障等级',prop:'protectionLevel',selected:1},
		{label:'基站地形',prop:'terrain',selected:1},
		{label:'气候分区',prop:'weather',selected:1},
		{label:'经度',prop:'lng',selected:1},
		{label:'纬度',prop:'lat',selected:1},
		{label:'FSU是否安装',prop:'fsuInstallStatus',selected:1},
		{label:'FSU状态',prop:'fsuStatus',selected:1},
		{label:'FSU交维时间',prop:'fsuHandoverTime',selected:1},
	],
	selectKey:{}
};
